# Abstract {.unnumbered}

**Background**. Since 2021, monoclonal antibody (mAb) therapy has effectively treated patients with mild-to-moderate COVID-19 infections at risk of more severe infections. Clinical researchers have studied mAb effectiveness in reducing hospitalization and mortality. This study further examines the effectiveness of available mAb therapies in reducing rehospitalization and mortality over 19 months in the greater Seattle area.

**Methods**. We conducted an IRB-approved retrospective chart review of nonhospitalized adult patients who presented to emergency departments (ED) in the greater Seattle area from March 2021-October 2022 with mild-to-moderate COVID-19 infections. We compared mAbs treated patients to non-treated eligible patients with 28-day rehospitalization and all-cause hospital mortality as primary outcomes Secondary outcomes were rates of inpatient admission, intensive care, and mechanical ventilation. Propensity score matching and logistic regression models were used to control for demographic and comorbidities.

**Results**. 21,139 patients were included. MAb treatment was associated with reduced significantly odds of 28-day rehospitalization (adjusted odds ratio [aOR] 0.66, (95% CI 0.49-0.87), P = 0.004), mortality (adjusted odds ratio [aOR] 0.32, (95% CI 0.19-0.51), P < 0.001), and inpatient admissions (adjusted odds ratio [aOR] 0.43, (95% CI 0.31-0.61), P < 0.001).

**Conclusions**. In a single hospital system, From March 2021 through October 2022, mAbs treatments were associated with reduced rehospitalization, mortality, and inpatient admission in patients with mild-to-moderate COVID-19 infections in western Washington. Our study contributes real world evidence to the medical literature on the efficacy of monoclonal antibodies as a treatment for outpatients with mild-to-moderate COVID-19 at risk of developing severe infection. 

**Key Words** comorbidities, COVID-19, mild-to-moderate, monoclonal antibody therapy, mortality, rehospitalization