# Introduction {.unnumbered}

Since early 2021, monoclonal antibody (mAb) therapy has emerged as an efficacious intervention for patients with mild-to-moderate COVID-19 infections, particularly those at high risk of progressing to more severe infections. With favorable results from clinical trials, the U.S. Food and Drug Administration (FDA) issued Emergency Use Authorizations for a series of mAb treatments: casirivimab-imdevimab (REGEN-COV) in November 2020 [@OShaughnessy-eua091; @Weinrich-2021], bamlanivimab plus etesevimab (BAM+ETE) in February 2021 [@OShaughnessy-eua094; @Dougan-2022], sotrovimab (SOT) in May 2021 [@OShaughnessy-eua100; @Gupta-2022], then bebtelovimab (BEB) in February 2022 [@OShaughnessy-eua111; @lilly2020study]. 
As these therapeutic agents became readily available, clinicians and researchers embarked on comprehensive investigations into their impact on hospitalization rates and mortality outcomes. In spring 2021, bamlanivimab was associated with reduced rehospitalizations and, in most cases, mortality within 28 days [@bariola2021impact; @ganesh2021intravenous; @iqbal2021efficacy; @melton2021impact]. Later, in the fall of 2021, sotrovimab use also seemed to decrease odds of hospitalization and mortality [@aggarwal2022real; @cheng2023real]. Later studies of bebtelovimab use, however, found mixed results [@molina2023real; @sridhara2023lack].

More recent studies have examined the effect of all available mAb agents, along with COVID vaccinations, on patient outcomes over a longer period of the pandemic. These studies have also found decreased odds of rehospitalization and mortality in treated patients across phases of the pandemic [@wynia2023real; @kip2023evolving].

This study delves deeper into the effectiveness of accessible mAb therapies and their synergistic interactions with COVID-19 vaccinations in mitigating rehospitalization and mortality over a span of 19 months, within the encompassing landscape of greater Seattle in western Washington.