# Methods {.unnumbered}

## Patient population

We conducted a propensity-matched, retrospective, observational study using data from our electronic medical record system (EHR; Epic). This study was approved by the institutional review board of Providence-St. Joseph Health Care, a large multistate healthcare organization. Individual patient consent was not required. The setting for this study was Providence Swedish Health Services, a regional healthcare network in the Puget Sound area of western Washington which includes approximately 1,570 licensed beds. The network includes seven EDs that were host to 221,000 ED visits in 2022.

We identified a study population of adult patients who were eligible for monoclonal antibody therapy. Our inclusion criteria were adult outpatients who presented to an ED from March 25, 2021 (the date of the first mAb administration) through October 31, 2022, with mild-to-moderate SARS-CoV-2 infections and at least one of the following active comorbidities: arrythmia, cancer, cardiovascular dysfunction, diabetes, immunosuppression, obesity, renal dysfunction, a respiratory disorder, and/or tobacco use. We excluded patients who lacked all of the aforementioned comorbidities, who received oxygen therapy on their first ED visit, and who were admitted to the hospital on their first ED visit. Baseline demographic data we collected included age, sex, and race. We also collected acuity levels and dates of COVID-19 vaccinations.

## Outcomes

Our two primary outcomes were 28-day rehospitalization and all-cause hospital mortality. Secondary outcomes were any days as a hospital inpatient, in intensive care, and/or on mechanical ventilation following discharge from their first ED visit.

## Variable definitions

We defined our first primary outcome of 28-day rehospitalization as admission to an ED or an inpatient hospital admission for a COVID-19-related reason within 28 days of discharge from the first ED visit. We operationalized this outcome as a dichotomy in which 1 indicated readmission to an ED or hospital within 28 days and 0 all others. Our second primary outcome of mortality we defined as all-cause hospital mortality, and this we measured as a dichotomy in which 1 indicated all-cause hospital mortality in the time between discharge from the ED visit and the end of the study period, and 0 all others. We defined a COVID-19-related reason as either (1) a positive SARS-CoV-2 lab test undertaken within the hospital encounter, (2) a SARS-CoV-2 infection documented in the ED infectious risk screening, and/or (3) a COVID-19-related ED encounter diagnosis using ICD10 codes (U00, U09, U49, U50, U85, J12.82, M35.81, Z20.822). To account for historical change in the pandemic, we calculated the time in months from the date of the first mAb approval (November 21, 2020) to the date of the hospital encounter (whether an ED visit or inpatient admission). Because our secondary outcomes were skewed, we measured these as dichotomies in which 1 indicated any inpatient days, ICU days, and/or mechanical ventilation days, and 0 all others.

Our covariates of interest included sex, race, age, comorbidities, mAb treatment status, acuity level, and number of vaccinations at the first ED visit. We coded sex as a dichotomy in which a value of 1 indicated male and 0 female, and race as a dichotomy in which 1 = nonwhite and 0 = white. We dichotomized age into patients below or at least 65 years of age at the time of the hospital encounter. For comorbidities we used ICD10 codes on the patient problem list. We coded each comorbidity as a dichotomy in which 1 indicated active presence within the study period and 0 nonpresence. We identified mAb-treated patients from documented administrations of mAb infusions on the first ED visit. Treatments included bamlanivimab, casirivimab + imdevimab, bamlanivimab + etesevimab, sotrovimab, and bebtelovimab. Acuity level we coded into the following 4-point ordinal scale of increasing urgency: 1 = Non-urgent, 2 = Less urgent, 3 = Urgent, 4 = Emergent or Immediate. Finally, we measured vaccination status as the cumulative count of documented COVID-19 vaccination dates received by the hospital encounter.

## Statistical analysis

We first reported baseline characteristics and clinical indicators for the treated and untreated patients both before and after propensity score matching. We reported as descriptive statistics means and standard deviations for continuous variables and frequencies and percentages for categorical variables.

We estimated propensity scores for receipt of mAb therapy using the 1:1 nearest neighbor method without replacement with logistic regression. We matched on the factors shown in the descriptive analyses to be statistically significant differences between the treated and untreated patients in the full unmatched sample. These factors included age, race, immunosuppression, renal disorder, respiratory disorder, tobacco use, months into availability of mAb treatment, acuity level, and number of vaccinations. To estimate the treatment effect and its standard error, we fit logistic regression models for our outcomes on mAb treatment and any covariates remaining unbalanced after propensity score matching. We conducted all statistical analyses in RStudio [@RStudio]. For propensity score matching we used the MatchIt package [@MatchIt].