# Results {.unnumbered}

Between March 2021 and October 2022, a total of 21,139 patients met our inclusion criteria and were included the study. Upon propensity matching, 1,349 patients were included in the primary matched cohort (1,349 mAb-treated; 1,349 untreated). The propensity score matching diminished the imbalance in most of the key covariates, including age, race, immunosuppression, renal disorder, respiratory disorder, tobacco use, months into availability of mAb treatment, acuity level, and number of vaccinations. However, the propensity matched sample did differ significantly in months into mAb availability and number of COVID-19 vaccinations. Measures of association are available in Table 1.

## Characteristics of the mAb patients in the primary cohort

In the propensity-matched cohort, mAb-treated patients reflected characteristics consistent with patients at a high risk for progression to severe COVID-19 (Table 1). Among patients who received mAb therapy (n = 1,349), 805 (60%) were aged 65 years or older, 387 (29%) were nonwhite, 136 (10%) were immunosuppressed, 275 (20%) suffered from renal disorders, and 452 (34%) suffered from respiratory disorders.

Table 1. Patient Characteristics and Covariate Balance Before and After Propensity Matching

------------------------------------------------------------------------

```{=html}
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings gt_spanner_row">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id="<strong>Characteristic</strong>"><strong>Characteristic</strong></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" scope="colgroup" id="<strong>Before propensity matching</strong>">
        <span class="gt_column_spanner"><strong>Before propensity matching</strong></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" scope="colgroup" id="<strong>After propensity matching</strong>">
        <span class="gt_column_spanner"><strong>After propensity matching</strong></span>
      </th>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>Treated</strong>, N = 1,349<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>Treated</strong>, N = 1,349<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>Untreated</strong>, N = 19,790<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>Untreated</strong>, N = 19,790<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>2</sup></span>"><strong>p</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>2</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>Treated</strong>, N = 1,349<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>Treated</strong>, N = 1,349<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>Untreated</strong>, N = 1,349<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>Untreated</strong>, N = 1,349<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>2</sup></span>"><strong>p</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>2</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Male</td>
<td headers="stat_1_1" class="gt_row gt_center">636 (47%)</td>
<td headers="stat_2_1" class="gt_row gt_center">8,273 (42%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">636 (47%)</td>
<td headers="stat_2_2" class="gt_row gt_center">614 (46%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.4</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Nonwhite</td>
<td headers="stat_1_1" class="gt_row gt_center">387 (29%)</td>
<td headers="stat_2_1" class="gt_row gt_center">7,743 (39%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">387 (29%)</td>
<td headers="stat_2_2" class="gt_row gt_center">367 (27%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.4</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Age 65+</td>
<td headers="stat_1_1" class="gt_row gt_center">805 (60%)</td>
<td headers="stat_2_1" class="gt_row gt_center">7,286 (37%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">805 (60%)</td>
<td headers="stat_2_2" class="gt_row gt_center">839 (62%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.2</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Arrythmia</td>
<td headers="stat_1_1" class="gt_row gt_center">305 (23%)</td>
<td headers="stat_2_1" class="gt_row gt_center">3,150 (16%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">305 (23%)</td>
<td headers="stat_2_2" class="gt_row gt_center">296 (22%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.7</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Cancer</td>
<td headers="stat_1_1" class="gt_row gt_center">186 (14%)</td>
<td headers="stat_2_1" class="gt_row gt_center">1,801 (9.1%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">186 (14%)</td>
<td headers="stat_2_2" class="gt_row gt_center">174 (13%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.5</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Cardiovascular disease</td>
<td headers="stat_1_1" class="gt_row gt_center">777 (58%)</td>
<td headers="stat_2_1" class="gt_row gt_center">8,965 (45%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">777 (58%)</td>
<td headers="stat_2_2" class="gt_row gt_center">744 (55%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.2</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Diabetes</td>
<td headers="stat_1_1" class="gt_row gt_center">250 (19%)</td>
<td headers="stat_2_1" class="gt_row gt_center">2,814 (14%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">250 (19%)</td>
<td headers="stat_2_2" class="gt_row gt_center">233 (17%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.4</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Immunosuppressed</td>
<td headers="stat_1_1" class="gt_row gt_center">136 (10%)</td>
<td headers="stat_2_1" class="gt_row gt_center">603 (3.0%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">136 (10%)</td>
<td headers="stat_2_2" class="gt_row gt_center">140 (10%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.8</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Obese</td>
<td headers="stat_1_1" class="gt_row gt_center">522 (39%)</td>
<td headers="stat_2_1" class="gt_row gt_center">8,679 (44%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">522 (39%)</td>
<td headers="stat_2_2" class="gt_row gt_center">537 (40%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.6</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Renal disease</td>
<td headers="stat_1_1" class="gt_row gt_center">275 (20%)</td>
<td headers="stat_2_1" class="gt_row gt_center">2,460 (12%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">275 (20%)</td>
<td headers="stat_2_2" class="gt_row gt_center">255 (19%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.3</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Respiratory disease</td>
<td headers="stat_1_1" class="gt_row gt_center">452 (34%)</td>
<td headers="stat_2_1" class="gt_row gt_center">7,040 (36%)</td>
<td headers="p.value_1" class="gt_row gt_center">0.12</td>
<td headers="stat_1_2" class="gt_row gt_center">452 (34%)</td>
<td headers="stat_2_2" class="gt_row gt_center">412 (31%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.10</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Tobacco user</td>
<td headers="stat_1_1" class="gt_row gt_center">47 (3.5%)</td>
<td headers="stat_2_1" class="gt_row gt_center">2,206 (11%)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">47 (3.5%)</td>
<td headers="stat_2_2" class="gt_row gt_center">34 (2.5%)</td>
<td headers="p.value_2" class="gt_row gt_center">0.14</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Months since mAb approval</td>
<td headers="stat_1_1" class="gt_row gt_center">15 (5)</td>
<td headers="stat_2_1" class="gt_row gt_center">13 (5)</td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center">15 (5)</td>
<td headers="stat_2_2" class="gt_row gt_center">14 (5)</td>
<td headers="p.value_2" class="gt_row gt_center">0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Acuity level</td>
<td headers="stat_1_1" class="gt_row gt_center"></td>
<td headers="stat_2_1" class="gt_row gt_center"></td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center"></td>
<td headers="stat_2_2" class="gt_row gt_center"></td>
<td headers="p.value_2" class="gt_row gt_center">0.13</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;1</td>
<td headers="stat_1_1" class="gt_row gt_center">5 (0.4%)</td>
<td headers="stat_2_1" class="gt_row gt_center">179 (0.9%)</td>
<td headers="p.value_1" class="gt_row gt_center"></td>
<td headers="stat_1_2" class="gt_row gt_center">5 (0.4%)</td>
<td headers="stat_2_2" class="gt_row gt_center">14 (1.0%)</td>
<td headers="p.value_2" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;2</td>
<td headers="stat_1_1" class="gt_row gt_center">173 (13%)</td>
<td headers="stat_2_1" class="gt_row gt_center">3,168 (16%)</td>
<td headers="p.value_1" class="gt_row gt_center"></td>
<td headers="stat_1_2" class="gt_row gt_center">173 (13%)</td>
<td headers="stat_2_2" class="gt_row gt_center">156 (12%)</td>
<td headers="p.value_2" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;3</td>
<td headers="stat_1_1" class="gt_row gt_center">923 (68%)</td>
<td headers="stat_2_1" class="gt_row gt_center">11,756 (59%)</td>
<td headers="p.value_1" class="gt_row gt_center"></td>
<td headers="stat_1_2" class="gt_row gt_center">923 (68%)</td>
<td headers="stat_2_2" class="gt_row gt_center">916 (68%)</td>
<td headers="p.value_2" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;4</td>
<td headers="stat_1_1" class="gt_row gt_center">248 (18%)</td>
<td headers="stat_2_1" class="gt_row gt_center">4,687 (24%)</td>
<td headers="p.value_1" class="gt_row gt_center"></td>
<td headers="stat_1_2" class="gt_row gt_center">248 (18%)</td>
<td headers="stat_2_2" class="gt_row gt_center">263 (19%)</td>
<td headers="p.value_2" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">COVID vaccinations</td>
<td headers="stat_1_1" class="gt_row gt_center"></td>
<td headers="stat_2_1" class="gt_row gt_center"></td>
<td headers="p.value_1" class="gt_row gt_center">&lt;0.001</td>
<td headers="stat_1_2" class="gt_row gt_center"></td>
<td headers="stat_2_2" class="gt_row gt_center"></td>
<td headers="p.value_2" class="gt_row gt_center">0.040</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;0</td>
<td headers="stat_1_1" class="gt_row gt_center">1,298 (96%)</td>
<td headers="stat_2_1" class="gt_row gt_center">18,256 (92%)</td>
<td headers="p.value_1" class="gt_row gt_center"></td>
<td headers="stat_1_2" class="gt_row gt_center">1,298 (96%)</td>
<td headers="stat_2_2" class="gt_row gt_center">1,299 (96%)</td>
<td headers="p.value_2" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;1</td>
<td headers="stat_1_1" class="gt_row gt_center">14 (1.0%)</td>
<td headers="stat_2_1" class="gt_row gt_center">420 (2.1%)</td>
<td headers="p.value_1" class="gt_row gt_center"></td>
<td headers="stat_1_2" class="gt_row gt_center">14 (1.0%)</td>
<td headers="stat_2_2" class="gt_row gt_center">19 (1.4%)</td>
<td headers="p.value_2" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;2</td>
<td headers="stat_1_1" class="gt_row gt_center">4 (0.3%)</td>
<td headers="stat_2_1" class="gt_row gt_center">408 (2.1%)</td>
<td headers="p.value_1" class="gt_row gt_center"></td>
<td headers="stat_1_2" class="gt_row gt_center">4 (0.3%)</td>
<td headers="stat_2_2" class="gt_row gt_center">8 (0.6%)</td>
<td headers="p.value_2" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;3</td>
<td headers="stat_1_1" class="gt_row gt_center">9 (0.7%)</td>
<td headers="stat_2_1" class="gt_row gt_center">489 (2.5%)</td>
<td headers="p.value_1" class="gt_row gt_center"></td>
<td headers="stat_1_2" class="gt_row gt_center">9 (0.7%)</td>
<td headers="stat_2_2" class="gt_row gt_center">14 (1.0%)</td>
<td headers="p.value_2" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;4</td>
<td headers="stat_1_1" class="gt_row gt_center">24 (1.8%)</td>
<td headers="stat_2_1" class="gt_row gt_center">217 (1.1%)</td>
<td headers="p.value_1" class="gt_row gt_center"></td>
<td headers="stat_1_2" class="gt_row gt_center">24 (1.8%)</td>
<td headers="stat_2_2" class="gt_row gt_center">9 (0.7%)</td>
<td headers="p.value_2" class="gt_row gt_center"></td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="7"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> n (%); Mean (SD)</td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="7"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>2</sup></span> Pearson’s Chi-squared test; Wilcoxon rank sum test</td>
    </tr>
  </tfoot>
</table>
```
## Primary and secondary outcomes

The crude rates of rehospitalization, mortality, and inpatient outcomes are shown in Table 2. During the study period, the incidence of 28-day hospitalization in our primary matched cohort was 9.4% (n = 127/1,349) for untreated patients compared to 6.3% (n = 85/1,349) among mAb-treated patients. The mortality rate for untreated patients was 5.3% (n = 41/1,349) compared to 1.7% (n = 23/1,349) for mAb-treated patients. The rate of inpatient admission for untreated patients was 8.6% (n = 116/1,349) compared to 3.8% (n = 51/1,349) for mAb-treated patients. Rates of ICU and mechanical ventilation did not differ significantly by treatment group.

Table 2. Primary and Secondary Outcomes for Primary Matched Cohort

------------------------------------------------------------------------

```{=html}

<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="<strong>Characteristic</strong>"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>Treated</strong>, N = 1,349<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>Treated</strong>, N = 1,349<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>Untreated</strong>, N = 1,349<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>Untreated</strong>, N = 1,349<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p-value</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>2</sup></span>"><strong>p</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>2</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Primary outcomes">Primary outcomes</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Primary outcomes  label" class="gt_row gt_left" style="font-style: italic;">28-Day Readmission</td>
<td headers="Primary outcomes  stat_1" class="gt_row gt_center">85 (6.3%)</td>
<td headers="Primary outcomes  stat_2" class="gt_row gt_center">127 (9.4%)</td>
<td headers="Primary outcomes  p.value" class="gt_row gt_center">0.003</td></tr>
    <tr><td headers="Primary outcomes  label" class="gt_row gt_left" style="font-style: italic;">Mortality</td>
<td headers="Primary outcomes  stat_1" class="gt_row gt_center">23 (1.7%)</td>
<td headers="Primary outcomes  stat_2" class="gt_row gt_center">71 (5.3%)</td>
<td headers="Primary outcomes  p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Secondary outcomes">Secondary outcomes</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Secondary outcomes  label" class="gt_row gt_left" style="font-style: italic;">Any days as hospital inpatient</td>
<td headers="Secondary outcomes  stat_1" class="gt_row gt_center">51 (3.8%)</td>
<td headers="Secondary outcomes  stat_2" class="gt_row gt_center">116 (8.6%)</td>
<td headers="Secondary outcomes  p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="Secondary outcomes  label" class="gt_row gt_left" style="font-style: italic;">Any days in ICU</td>
<td headers="Secondary outcomes  stat_1" class="gt_row gt_center">10 (0.7%)</td>
<td headers="Secondary outcomes  stat_2" class="gt_row gt_center">20 (1.5%)</td>
<td headers="Secondary outcomes  p.value" class="gt_row gt_center">0.066</td></tr>
    <tr><td headers="Secondary outcomes  label" class="gt_row gt_left" style="font-style: italic;">Any days on ventilator</td>
<td headers="Secondary outcomes  stat_1" class="gt_row gt_center">4 (0.3%)</td>
<td headers="Secondary outcomes  stat_2" class="gt_row gt_center">4 (0.3%)</td>
<td headers="Secondary outcomes  p.value" class="gt_row gt_center">&gt;0.9</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> n (%)</td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>2</sup></span> Pearson’s Chi-squared test</td>
    </tr>
  </tfoot>
</table>
```
The adjusted analyses are presented in Table 3. Treatment with mAb was associated with reduced odds of 28-day rehospitalization (adjusted odds ratio \[aOR\] 0.66, \[95% confidence interval (CI)\] 0.49-0.87), *P* = 0.004). Mortality rates also differed significantly between the two groups. Treatment with mAb was associated with reduced odds of mortality (adjusted odds ratio \[aOR\] 0.32, \[95% confidence interval (CI)\] 0.19-0.51), *P* \< 0.001). Treatment was also associated with reduced odds of inpatient admissions (adjusted odds ratio \[aOR\] 0.43, \[95% confidence interval (CI)\] 0.31-0.61), *P* \< 0.001).[^results-1]

[^results-1]: In these adjusted analyses, months since mAb approval of the first ED visit remained a statistically significant covariate after controlling for mAb treatment and number of COVID vaccinations. Months since mAb approval was associated with significantly but slightly reduced odds of rehospitalization (adjusted odds ratio \[aOR\] 0.97, \[95% confidence interval (CI)\] 0.94-1.00), *P* = 0.038) and inpatient admissions (adjusted odds ratio \[aOR\] 0.93, \[95% confidence interval (CI)\] 0.90-0.96), *P* \< 0.001).

Table 3. Adjusted Odds Ratios

------------------------------------------------------------------------

```{=html}
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings gt_spanner_row">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id="<strong>Characteristic</strong>"><strong>Characteristic</strong></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" scope="colgroup" id="<strong>28-Day Rehospitalization</strong>">
        <span class="gt_column_spanner"><strong>28-Day Rehospitalization</strong></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" scope="colgroup" id="<strong>Mortality</strong>">
        <span class="gt_column_spanner"><strong>Mortality</strong></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" scope="colgroup" id="<strong>Inpatient</strong>">
        <span class="gt_column_spanner"><strong>Inpatient</strong></span>
      </th>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>OR</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>OR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p-value</strong>"><strong>p</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>OR</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>OR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p-value</strong>"><strong>p</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>OR</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>OR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p-value</strong>"><strong>p</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Received mAb</td>
<td headers="estimate_1" class="gt_row gt_center">0.66</td>
<td headers="ci_1" class="gt_row gt_center">0.49, 0.87</td>
<td headers="p.value_1" class="gt_row gt_center" style="font-weight: bold;">0.004</td>
<td headers="estimate_2" class="gt_row gt_center">0.32</td>
<td headers="ci_2" class="gt_row gt_center">0.19, 0.51</td>
<td headers="p.value_2" class="gt_row gt_center" style="font-weight: bold;">&lt;0.001</td>
<td headers="estimate_3" class="gt_row gt_center">0.43</td>
<td headers="ci_3" class="gt_row gt_center">0.31, 0.61</td>
<td headers="p.value_3" class="gt_row gt_center" style="font-weight: bold;">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Months since mAb approval</td>
<td headers="estimate_1" class="gt_row gt_center">0.97</td>
<td headers="ci_1" class="gt_row gt_center">0.94, 1.00</td>
<td headers="p.value_1" class="gt_row gt_center" style="font-weight: bold;">0.038</td>
<td headers="estimate_2" class="gt_row gt_center">0.96</td>
<td headers="ci_2" class="gt_row gt_center">0.92, 1.00</td>
<td headers="p.value_2" class="gt_row gt_center">0.080</td>
<td headers="estimate_3" class="gt_row gt_center">0.93</td>
<td headers="ci_3" class="gt_row gt_center">0.90, 0.96</td>
<td headers="p.value_3" class="gt_row gt_center" style="font-weight: bold;">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">COVID vaccinations</td>
<td headers="estimate_1" class="gt_row gt_center">1.16</td>
<td headers="ci_1" class="gt_row gt_center">0.90, 1.42</td>
<td headers="p.value_1" class="gt_row gt_center">0.2</td>
<td headers="estimate_2" class="gt_row gt_center">1.03</td>
<td headers="ci_2" class="gt_row gt_center">0.63, 1.44</td>
<td headers="p.value_2" class="gt_row gt_center">&gt;0.9</td>
<td headers="estimate_3" class="gt_row gt_center">1.05</td>
<td headers="ci_3" class="gt_row gt_center">0.74, 1.37</td>
<td headers="p.value_3" class="gt_row gt_center">0.8</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="10"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
```
